language: python
python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r requirements.dev.txt

script:
  - pylama oscli
  - python debug.py config ensure
  - nosetests tests --with-coverage --cover-package oscli

after_success:
  - coveralls
